#Postgres persistence
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/InkDB
    username: postgres
    password: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: webreport
server:
  port: 8001
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka 